### ISSUE TITLE
Games with `None` as banner come up as having the Command and Conquer: Red Alert 2 logo

### ISSUE THREAD

**Issue by Steffo99** [lutris/website#641] opened 2022-09-12 16:42 UTC
## Screenshot

![Insaniquarium! Deluxe having the C&C:RA2 logo](https://user-images.githubusercontent.com/1540885/189709574-b81ff99c-8f38-48ef-858c-18389655853f.png "Insaniquarium! Deluxe having the C&C:RA2 logo")

## Reason

`https://lutris.net/games/banner/None.jpg` is an image of the C&C:RA2 logo!

![](https://lutris.net/games/banner/None.jpg)

**Comment by danieljohnson2** [comment] 2022-09-13 23:05
That is hilarious!

But I do not understand how you create a game like this. What's the reproduction?

**Comment by Steffo99** [comment] 2022-09-14 01:53
Wait, it's now Darkest Dungeon?!?

The `None` pops up when submitting a contribution to a game, but I'm not sure where the banner comes from...?

**Comment by Steffo99** [comment] 2022-09-14 03:16
To be clear, I mean after pressing the "Suggest Changes" button on a game and successfully completing the form, then by visiting this page: `https://lutris.net/user/YOUR-USERNAME/submissions/`

**Comment by dblblaster** [comment] 2022-10-21 07:56
I tried to submit a banner for [this one](https://lutris.net/games/atomic-bomberman/) and, since it's not yet been approved, the image is still the "None.jpg" so now every now and then under my "submissions" tab it will show a random banner. https://lutris.net/games/banner/None.jpg currently shows a "Majikoi!" banner.

**Comment by arft1kwerg** [comment] 2023-05-22 18:26
Having similar issue. Uploaded a bunch of banner images for a number of games, but in the Submit section under account it shows random images instead. Have seen Kane's Wrath, Billy the Hatcher, Jagex Launcher, and many many other completely wrong images being displayed.

![Skärmbild från 2023-05-22 20-19-55](https://github.com/lutris/website/assets/29517963/9a3b1636-0e27-4202-9082-f1622c4bf993)

**Comment by strycore** [comment] 2023-05-24 11:04
I pushed a fix for that, the issue was the copy of the game containing the new info didn't have a slug field so it showed None.jpg

**Closed by strycore** 2023-05-24 11:04 UTC
