### ISSUE TITLE
A way to report duplicate game pages

### ISSUE THREAD

**Issue by skyace65** [lutris/website#353] opened 2019-04-24 00:43 UTC
When GOG support was added a lot of duplicate pages were created and as of right now there's no way to report them. On Discord I asked in the requests and feedback channel if that was the place to report duplicates and got no response.

Some Duplicate pages:
[Rogue Squardron 3D(GOG)](https://lutris.net/games/star-wars-rogue-squadron-3d/) [Rogue Squadron 3D(Steam)](https://lutris.net/games/star-warstm-rogue-squadron-3d/)
[X-wing Alliance (GOG)](https://lutris.net/games/star-wars-x-wing-alliance/) [X-wing Alliance (Steam)](https://lutris.net/games/star-warstm-x-wing-alliancetm/)
[Wing Commander 3 (GOG)](https://lutris.net/games/wing-commander-3-heart-of-the-tiger/) [Wing Commander 3 (Pre-GOG page)](https://lutris.net/games/wing-commander-iii-heart-of-the-tiger/)
[Lego Batman 2 (GOG)](https://lutris.net/games/lego-batman-2-dc-super-heroes/) [Lego Batman 2 (Steam)](https://lutris.net/games/lego-batman-2/)

Even if it's not a built in feature on the website and just a channel on discord that would be great.

**Comment by RobLoach** [comment] 2019-04-24 01:40
We should probably roll with the one with the most users, set the GOG ID, and delete the old ones.

I'm unable to delete, only unpublish.

**Comment by testman42** [comment] 2019-05-01 21:45
I do believe that this is a duplicate of #208

**Closed** 2019-05-02 04:20 UTC
