### ISSUE TITLE
Improve installer moderation

### ISSUE THREAD

**Issue by tannisroot** [lutris/website#254] opened 2018-12-08 06:27 UTC
Right now, communication between moderators and installer creators is very poor.
Here's how it can be improved:
* Introduce `Reject` functionality that would put the installer in limbo until all issues with it were resolved
* Add comment box when accepting/rejecting installer (mandatory when rejecting)
* Notify installer creators when their script gets accepted/rejected through email (which is actually https://github.com/lutris/website/issues/233) , include commentary from the moderator with it and congratulate the creator/suggest to edit the script and resubmit it for moderation.

**Comment by strycore** [comment] 2022-01-10 21:51
duplicate of #206

**Closed by strycore** 2022-01-10 21:51 UTC
Labels: Installers
