### ISSUE TITLE
Allow users to suggest new links for installers through "Suggest changes"

### ISSUE THREAD

**Issue by Faalagorn** [lutris/website#372] opened 2019-07-13 18:58 UTC
Kinda related to #61 but available for users to add through "Suggest changes". Also related is #243 – ability for users to add icons.

Currently it's only possible to suggest new/improved fields for Title, Release year, Developer, Publisher, Website, Platforms, Genres, Description and Banner image. It's not possible to suggest new icons or add any other external links than the main website (PCGW, MobyGames, Wikipedia, WineHQ, Steam/SteamDB/ProtonDB, GOG, Humble, ITAD etc.) that some games on website already have. For example, I couldn't suggest to add https://en.wikipedia.org/wiki/Escape_from_Tarkov when I suggested changes back there and it still seems to not be possible to do.

Since the suggestion go through moderation anyway, it would be nice if users had ability to suggest/add such links through the website interface.

**Comment by strycore** [comment] 2022-01-10 23:55
duplicate of #268

**Closed** 2022-01-10 23:56 UTC
