### ISSUE TITLE
Tell users who try making installers with an existing slug that they're wrong

### ISSUE THREAD

**Issue by soredake** [lutris/website#124] opened 2017-12-02 16:47 UTC
After trying to change installer slug of winesteam version to `euro-truck-simulator-2-winesteam` of this game https://lutris.net/games/euro-truck-simulator-2/ it still remains `euro-truck-simulator-2-steam-1`. @strycore

**Comment by strycore** [comment] 2017-12-02 23:16
Yep, there is already a installer for Steam so that's the indented behavior.

Not that there shouldn't be 2 installers for the Steam version, that would be confusing to user, please edit the existing one instead of creating a new one.

**Comment by soredake** [comment] 2017-12-03 08:21
@strycore maybe better to leave some note that you can't change slug manually or make slug field non-editable to not confuse people?

**Comment by strycore** [comment] 2017-12-09 22:29
There should be some sort of warning, yes. The problem is not about the slug being editable, it *should* be, the problem is with 2 installers having the same slug, this shouldn't happen.

**Comment by strycore** [comment] 2018-09-08 18:55
Fixed by https://github.com/lutris/website/commit/86b5a4200c75d96c45a4c99a9d5b1fdeb8084a2d

**Closed by strycore** 2018-09-08 18:55 UTC
Labels: BMU2018
