### ISSUE TITLE
uploading jpg become blackbox

### ISSUE THREAD

**Issue by axet** [lutris/website#426] opened 2020-04-23 08:22 UTC
Uploading this jpg fine at preview but blackbox after upload. This game:

https://lutris.net/games/frontier-elite-ii/

https://upload.wikimedia.org/wikipedia/en/3/32/Frontier_elite2_box.jpg

**Comment by strycore** [comment] 2022-01-11 05:16
duplicate of #611

**Closed by strycore** 2022-01-11 05:16 UTC
Labels: reviewed, banners
